### ISSUE TITLE
Spectral Range 

### ISSUE THREAD

**Issue by astroindhu** [planetserver/ps2-www-client#7]
Hi PS2 

@RamiroMF 

Unable to change the spectral range of M3 to 0.4-3 microns in the Range Charts 

Please fix the same 

Indhu

**Comment by RamiroMF** [comment]
This issue is related to the Moon client. The problem is that the original range at loading time is 1 to 1.85 microns whereas M3 ranges from 0.4 to 3 microns. Even changing the spectral range in the client, the plotting tool does not changes the range. @bangph would you be able to look at the issue and fix it?
Ramiro

**Comment by bangph** [comment]
I pulled the fix for it.
